/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package producer

import (
	"net/http"

	"free5gc/lib/http_wrapper"
	. "free5gc/lib/openapi/models"
	"free5gc/src/nssf/handler/message"
	"free5gc/src/nssf/logger"
)

// NSSAIAvailabilityUnsubscribe - Deletes an already existing NSSAI availability notification subscription
func NSSAIAvailabilityUnsubscribe(responseChan chan message.HandlerResponseMessage, subscriptionId string) {

	logger.Nssaiavailability.Infof("Request received - NSSAIAvailabilityUnsubscribe")

	var (
		status int
		d      ProblemDetails
	)

	status = subscriptionDelete(subscriptionId, &d)

	if status == http.StatusNoContent {
		responseChan <- message.HandlerResponseMessage{
			HttpResponse: &http_wrapper.Response{
				Header: nil,
				Status: status,
			},
		}
	} else {
		responseChan <- message.HandlerResponseMessage{
			HttpResponse: &http_wrapper.Response{
				Header: nil,
				Status: status,
				Body:   d,
			},
		}
	}
}
