/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nsselection

import (
	"github.com/gin-gonic/gin"

	"free5gc/lib/http_wrapper"
	"free5gc/src/nssf/handler"
	"free5gc/src/nssf/handler/message"
)

func ApiNetworkSliceInformationDocument(c *gin.Context) {
	var request interface{}
	req := http_wrapper.NewRequest(c.Request, request)

	msg := message.NewMessage(message.NSSelectionGet, req)

	handler.SendMessage(msg)
	rsp := <-msg.ResponseChan

	httpResponse := rsp.HttpResponse
	c.JSON(httpResponse.Status, httpResponse.Body)
}
