/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package nssaiavailability

import (
	"net/http"

	"github.com/gin-gonic/gin"

	"free5gc/lib/http_wrapper"
	"free5gc/src/nssf/handler"
	"free5gc/src/nssf/handler/message"
	"free5gc/src/nssf/logger"
)

func ApiSubscriptionIdDocument(c *gin.Context) {
	// Due to conflict of route matching, 'subscriptions' in the route is replaced with the existing wildcard ':nfId'
	nfId := c.Param("nfId")
	if nfId != "subscriptions" {
		c.JSON(http.StatusNotFound, gin.H{})
		logger.Nssaiavailability.Infof("404 Not Found")
		return
	}

	var request interface{}
	req := http_wrapper.NewRequest(c.Request, request)
	req.Params["subscriptionId"] = c.Param("subscriptionId")

	msg := message.NewMessage(message.NSSAIAvailabilityUnsubscribe, req)

	handler.SendMessage(msg)
	rsp := <-msg.ResponseChan

	httpResponse := rsp.HttpResponse
	c.JSON(httpResponse.Status, httpResponse.Body)
}
