/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package producer

import (
	"net/http"

	"github.com/free5gc/nssf/internal/logger"
	"github.com/free5gc/openapi/models"
	"github.com/free5gc/util/httpwrapper"
)

// HandleNSSAIAvailabilityPost - Creates subscriptions for notification about updates to NSSAI availability information
func HandleNSSAIAvailabilityPost(request *httpwrapper.Request) *httpwrapper.Response {
	logger.NssaiavailLog.Infof("Handle NSSAIAvailabilityPost")

	createData := request.Body.(models.NssfEventSubscriptionCreateData)

	// TODO: If NF consumer is not authorized to update NSSAI availability, return ProblemDetails with code 403 Forbidden

	response, problemDetails := NSSAIAvailabilityPostProcedure(createData)

	if response != nil {
		// TODO: Based on TS 29.531 5.3.2.3.1, add location header
		return httpwrapper.NewResponse(http.StatusCreated, nil, response)
	} else if problemDetails != nil {
		return httpwrapper.NewResponse(int(problemDetails.Status), nil, problemDetails)
	}
	problemDetails = &models.ProblemDetails{
		Status: http.StatusForbidden,
		Cause:  "UNSPECIFIED",
	}
	return httpwrapper.NewResponse(http.StatusForbidden, nil, problemDetails)
}
